Repository team-dopamine/husk-was, pull requests merged in 2024-10, with the labels that each got.

#2 Convetional Commit 설정
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#3 Entity Class 작성
  src/main/java/kr/husk/application/auth/entity/User.java
  src/main/java/kr/husk/application/auth/type/OAuthProvider.java
  src/main/java/kr/husk/application/connection/entity/Connection.java
  src/main/java/kr/husk/application/keychain/entity/KeyChain.java
  src/main/java/kr/husk/common/entity/BaseEntity.java
  src/main/resources/application.yml
Labels: enhancement

#5 인증 코드 관리 비즈니스 로직 구현
  build.gradle
  src/main/java/kr/husk/application/auth/service/AuthService.java
  src/main/java/kr/husk/domain/repository/AuthCodeRepository.java
  src/main/java/kr/husk/infrastructure/config/AuthConfig.java
  src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapAuthCodeRepository.java
Labels: enhancement, authorization

#6 DDD 원칙 준수를 위한 패키지 구조 변경
  README.md
  src/main/java/kr/husk/application/auth/service/AuthService.java
  src/main/java/kr/husk/domain/auth/entity/User.java
  src/main/java/kr/husk/domain/auth/repository/AuthCodeRepository.java
  src/main/java/kr/husk/domain/auth/type/OAuthProvider.java
  src/main/java/kr/husk/domain/connection/entity/Connection.java
  src/main/java/kr/husk/domain/keychain/entity/KeyChain.java
  src/main/java/kr/husk/infrastructure/config/AuthConfig.java
  src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapAuthCodeRepository.java
  src/main/resources/application.yml
Labels: documentation

#7 인증 코드 전송 API 구현
  build.gradle
  src/main/java/kr/husk/application/auth/dto/SendAuthCodeDto.java
  src/main/java/kr/husk/application/auth/service/AuthService.java
  src/main/java/kr/husk/domain/auth/repository/UserRepository.java
  src/main/java/kr/husk/domain/auth/service/UserService.java
  src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
  src/main/java/kr/husk/presentation/api/AuthApi.java
  src/main/java/kr/husk/presentation/rest/AuthController.java
  src/main/resources/application.yml
  src/test/java/kr/husk/presentation/rest/AuthControllerTest.java
Labels: enhancement, authorization

#8 feature/HK-46: 인증 코드 검증 API 구현
  src/main/java/kr/husk/application/auth/dto/VerifyAuthCodeDto.java
  src/main/java/kr/husk/application/auth/service/AuthService.java
  src/main/java/kr/husk/domain/auth/repository/AuthCodeRepository.java
  src/main/java/kr/husk/infrastructure/config/AuthConfig.java
  src/main/java/kr/husk/infrastructure/config/SecurityConfig.java
  src/main/java/kr/husk/infrastructure/persistence/ConcurrentMapAuthCodeRepository.java
  src/main/java/kr/husk/presentation/api/AuthApi.java
  src/main/java/kr/husk/presentation/rest/AuthController.java
  src/test/java/kr/husk/presentation/rest/AuthControllerTest.java
Labels: enhancement, authorization

#9 WAS 구성 데이터 및 중요 정보 중앙화를 위한 AWS Parameter Store 적용
  build.gradle
  src/main/resources/application.yml
Labels: enhancement
